site_name: NIST SP 800-53 Control Reference Site
site_url: https://grokify.github.io/go-nist-sp-800-53
docs_dir: docsrc
theme: readthedocs
markdown_extension:
    - attr_list
nav:
    - 'Home': 'index.md'
    - 'High Baseline':
        - 'AC: Access Control (46)': 'rev5/high_baseline/ac.md'
        - 'AT: Awareness and Training (6)': 'rev5/high_baseline/at.md'
        - 'AU: Audit and Accountability (25)': 'rev5/high_baseline/au.md'
        - 'CA: Assessment, Authorization, and Monitoring (14)': 'rev5/high_baseline/ca.md'
        - 'CM: Configuration Management (32)': 'rev5/high_baseline/cm.md'
        - 'CP: Contingency Planning (35)': 'rev5/high_baseline/cp.md'
        - 'IA: Identification and Authentication (26)': 'rev5/high_baseline/ia.md'
        - 'IR: Incident Response (18)': 'rev5/high_baseline/ir.md'
        - 'MA: Maintenance (12)': 'rev5/high_baseline/ma.md'
        - 'MP: Media Protection (10)': 'rev5/high_baseline/mp.md'
        - 'PE: Physical and Environmental Protection (25)': 'rev5/high_baseline/pe.md'
        - 'PL: Planning (7)': 'rev5/high_baseline/pl.md'
        - 'PS: Personnel Security (10)': 'rev5/high_baseline/ps.md'
        - 'RA: Risk Assessment (11)': 'rev5/high_baseline/ra.md'
        - 'SA: System and Services Acquisition (21)': 'rev5/high_baseline/sa.md'
        - 'SC: System and Communications Protection (30)': 'rev5/high_baseline/sc.md'
        - 'SI: System and Information Integrity (28)': 'rev5/high_baseline/si.md'
        - 'SR: Supply Chain Risk Management (14)': 'rev5/high_baseline/sr.md'
    - 'High Uplift':
        - 'AC: Access Control (7)': 'rev5/high_uplift/ac.md'
        - 'AT: Awareness and Training (0)': 'rev5/high_uplift/at.md'
        - 'AU: Audit and Accountability (9)': 'rev5/high_uplift/au.md'
        - 'CA: Assessment, Authorization, and Monitoring (4)': 'rev5/high_uplift/ca.md'
        - 'CM: Configuration Management (8)': 'rev5/high_uplift/cm.md'
        - 'CP: Contingency Planning (12)': 'rev5/high_uplift/cp.md'
        - 'IA: Identification and Authentication (2)': 'rev5/high_uplift/ia.md'
        - 'IR: Incident Response (5)': 'rev5/high_uplift/ir.md'
        - 'MA: Maintenance (3)': 'rev5/high_uplift/ma.md'
        - 'MP: Media Protection (3)': 'rev5/high_uplift/mp.md'
        - 'PE: Physical and Environmental Protection (7)': 'rev5/high_uplift/pe.md'
        - 'PL: Planning (0)': 'rev5/high_uplift/pl.md'
        - 'PS: Personnel Security (1)': 'rev5/high_uplift/ps.md'
        - 'RA: Risk Assessment (1)': 'rev5/high_uplift/ra.md'
        - 'SA: System and Services Acquisition (4)': 'rev5/high_uplift/sa.md'
        - 'SC: System and Communications Protection (5)': 'rev5/high_uplift/sc.md'
        - 'SI: System and Information Integrity (10)': 'rev5/high_uplift/si.md'
        - 'SR: Supply Chain Risk Management (2)': 'rev5/high_uplift/sr.md'
    - 'Moderate Baseline':
        - 'AC: Access Control (39)': 'rev5/moderate_baseline/ac.md'
        - 'AT: Awareness and Training (6)': 'rev5/moderate_baseline/at.md'
        - 'AU: Audit and Accountability (16)': 'rev5/moderate_baseline/au.md'
        - 'CA: Assessment, Authorization, and Monitoring (10)': 'rev5/moderate_baseline/ca.md'
        - 'CM: Configuration Management (24)': 'rev5/moderate_baseline/cm.md'
        - 'CP: Contingency Planning (23)': 'rev5/moderate_baseline/cp.md'
        - 'IA: Identification and Authentication (24)': 'rev5/moderate_baseline/ia.md'
        - 'IR: Incident Response (13)': 'rev5/moderate_baseline/ir.md'
        - 'MA: Maintenance (9)': 'rev5/moderate_baseline/ma.md'
        - 'MP: Media Protection (7)': 'rev5/moderate_baseline/mp.md'
        - 'PE: Physical and Environmental Protection (18)': 'rev5/moderate_baseline/pe.md'
        - 'PL: Planning (7)': 'rev5/moderate_baseline/pl.md'
        - 'PS: Personnel Security (9)': 'rev5/moderate_baseline/ps.md'
        - 'RA: Risk Assessment (10)': 'rev5/moderate_baseline/ra.md'
        - 'SA: System and Services Acquisition (17)': 'rev5/moderate_baseline/sa.md'
        - 'SC: System and Communications Protection (25)': 'rev5/moderate_baseline/sc.md'
        - 'SI: System and Information Integrity (18)': 'rev5/moderate_baseline/si.md'
        - 'SR: Supply Chain Risk Management (12)': 'rev5/moderate_baseline/sr.md'
    - 'Moderate Uplift':
        - 'AC: Access Control (28)': 'rev5/moderate_uplift/ac.md'
        - 'AT: Awareness and Training (1)': 'rev5/moderate_uplift/at.md'
        - 'AU: Audit and Accountability (6)': 'rev5/moderate_uplift/au.md'
        - 'CA: Assessment, Authorization, and Monitoring (2)': 'rev5/moderate_uplift/ca.md'
        - 'CM: Configuration Management (15)': 'rev5/moderate_uplift/cm.md'
        - 'CP: Contingency Planning (17)': 'rev5/moderate_uplift/cp.md'
        - 'IA: Identification and Authentication (8)': 'rev5/moderate_uplift/ia.md'
        - 'IR: Incident Response (6)': 'rev5/moderate_uplift/ir.md'
        - 'MA: Maintenance (5)': 'rev5/moderate_uplift/ma.md'
        - 'MP: Media Protection (3)': 'rev5/moderate_uplift/mp.md'
        - 'PE: Physical and Environmental Protection (8)': 'rev5/moderate_uplift/pe.md'
        - 'PL: Planning (1)': 'rev5/moderate_uplift/pl.md'
        - 'PS: Personnel Security (0)': 'rev5/moderate_uplift/ps.md'
        - 'RA: Risk Assessment (2)': 'rev5/moderate_uplift/ra.md'
        - 'SA: System and Services Acquisition (8)': 'rev5/moderate_uplift/sa.md'
        - 'SC: System and Communications Protection (15)': 'rev5/moderate_uplift/sc.md'
        - 'SI: System and Information Integrity (12)': 'rev5/moderate_uplift/si.md'
        - 'SR: Supply Chain Risk Management (1)': 'rev5/moderate_uplift/sr.md'
    - 'Low Baseline':
        - 'AC: Access Control (11)': 'rev5/low_baseline/ac.md'
        - 'AT: Awareness and Training (5)': 'rev5/low_baseline/at.md'
        - 'AU: Audit and Accountability (10)': 'rev5/low_baseline/au.md'
        - 'CA: Assessment, Authorization, and Monitoring (8)': 'rev5/low_baseline/ca.md'
        - 'CM: Configuration Management (9)': 'rev5/low_baseline/cm.md'
        - 'CP: Contingency Planning (6)': 'rev5/low_baseline/cp.md'
        - 'IA: Identification and Authentication (16)': 'rev5/low_baseline/ia.md'
        - 'IR: Incident Response (7)': 'rev5/low_baseline/ir.md'
        - 'MA: Maintenance (4)': 'rev5/low_baseline/ma.md'
        - 'MP: Media Protection (4)': 'rev5/low_baseline/mp.md'
        - 'PE: Physical and Environmental Protection (10)': 'rev5/low_baseline/pe.md'
        - 'PL: Planning (6)': 'rev5/low_baseline/pl.md'
        - 'PS: Personnel Security (9)': 'rev5/low_baseline/ps.md'
        - 'RA: Risk Assessment (8)': 'rev5/low_baseline/ra.md'
        - 'SA: System and Services Acquisition (9)': 'rev5/low_baseline/sa.md'
        - 'SC: System and Communications Protection (10)': 'rev5/low_baseline/sc.md'
        - 'SI: System and Information Integrity (6)': 'rev5/low_baseline/si.md'
        - 'SR: Supply Chain Risk Management (11)': 'rev5/low_baseline/sr.md'
